using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Threading;
using HalconDotNet;
using System.IO;
using Microsoft.VisualBasic;
namespace CameraImage
{
    public partial class Form1 : Form
    {
        HTuple hv_AcqHandle = null;
        bool isCamera = true;
        int a = 0, b = 0, c = 0;
        public Form1()
        {
            InitializeComponent();
            try
            {
                hv_AcqHandle = new HTuple();
                hv_AcqHandle.Dispose();
                HOperatorSet.OpenFramegrabber("MindVision17_X64", 1, 1, 0, 0, 0, 0, "progressive",
                 8, "Gray", -1, "false", "auto", "oufang", 0, -1, out hv_AcqHandle);
            }
            catch (Exception)
            {
                MessageBox.Show("未检测到相机！");
                isCamera = false;
            }          
        }       
        void returnNum()
        {
            TrueNum.Text = "0";WrongNum.Text = "0";allNum.Text = "0";
            a = 0; b = 0; c =0;
            pictureBox1.BackColor = Color.WhiteSmoke;
        }

        private void RealTimeSnap_Click(object sender, EventArgs e)
        {
            if (button2.Text == "开始")
            { timer1.Enabled = true;
            timer1.Start();
            button2.Text = "停止";
            returnNum();
            modelList.Enabled = false; }
            else 
            {  
                timer1.Enabled = false;
                timer1.Stop();
                button2.Text = "开始";
                modelList.Enabled = true;
            }
        }       

        private void btnAddModel_Click(object sender, EventArgs e)
        {
            string str = Interaction.InputBox("请输入模板名字", "创建模板", "", 100, 100);
            if (str == "") { str = "默认"; };
            if (false == Directory.Exists("f:modelFiles/model-" + str))
            {
              Directory.CreateDirectory("f:modelFiles/model-" + str);
            }
            else
            {
                MessageBox.Show("已有重复模板！");
                return;
            }
            HObject ho_Image = null, ho_Circle = null, ho_ImageReduced = null;
            HTuple hv_i = new HTuple();
            HTuple hv_Width = new HTuple(), hv_Height = new HTuple();
            HTuple hv_WindowHandle = new HTuple(), hv_Row = new HTuple();
            HTuple hv_Column = new HTuple(), hv_Radius = new HTuple();
            HTuple hv_ModelID = new HTuple();
            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_Image);
            HOperatorSet.GenEmptyObj(out ho_Circle);
            HOperatorSet.GenEmptyObj(out ho_ImageReduced);
            //Image Acquisition 01: Code generated by Image Acquisition 01



            //Image Acquisition 01: Do something
            for (hv_i = 1; (int)hv_i <= 4; hv_i = (int)hv_i + 1)
            {
                try
                {             
                HOperatorSet.GrabImageStart(hv_AcqHandle, -1);
                if ((int)hv_i!=1) MessageBox.Show("请将要识别物体顺时针旋转"+ ((int)hv_i-1) * 90+"度，再点击确定");
                else { MessageBox.Show("单击鼠标左键并拖动选择模板区域，右键确定！");}
                ho_Image.Dispose();
                HOperatorSet.GrabImageAsync(out ho_Image, hv_AcqHandle, -1);
                hv_Width.Dispose(); hv_Height.Dispose();
                HOperatorSet.GetImageSize(ho_Image, out hv_Width, out hv_Height);
                HOperatorSet.SetWindowAttr("background_color", "red");
                HOperatorSet.OpenWindow(0, 0, hv_Width + 1, hv_Height + 1, 0, "visible", "", out hv_WindowHandle);
                HOperatorSet.DispImage(ho_Image, hv_WindowHandle);
                HDevWindowStack.Push(hv_WindowHandle);
                hv_Row.Dispose(); hv_Column.Dispose(); hv_Radius.Dispose();
                HOperatorSet.DrawCircle(hv_WindowHandle, out hv_Row, out hv_Column, out hv_Radius);
                ho_Circle.Dispose();
                HOperatorSet.GenCircle(out ho_Circle, hv_Row, hv_Column, hv_Radius);
                ho_ImageReduced.Dispose();
                HOperatorSet.ReduceDomain(ho_Image, ho_Circle, out ho_ImageReduced);
                hv_ModelID.Dispose();
                HOperatorSet.CreateShapeModel(ho_ImageReduced, "auto", 0, (new HTuple(360)).TupleRad()
                    , "auto", "auto", "use_polarity", "auto", "auto", out hv_ModelID);
                HOperatorSet.WriteShapeModel(hv_ModelID, ("f:modelFiles/model-" + str+"/modle" + hv_i) + ".shm");
                
                }
                catch (Exception)
                {
                    MessageBox.Show("区域选择出错！请重新添加模板。");
                    foreach (string file in Directory.GetFileSystemEntries("f:modelFiles/model-" + str))
                    {
                        File.Delete(file);
                    };
                    Directory.Delete("f:modelFiles/model-" + str);
                    return;
                    throw;                   
                }
                finally {
                    HOperatorSet.CloseWindow(hv_WindowHandle);
                    ho_Image.Dispose();
                ho_Circle.Dispose();
                ho_ImageReduced.Dispose();
                hv_i.Dispose();
                hv_Width.Dispose();
                hv_Height.Dispose();
                hv_WindowHandle.Dispose();
                hv_Row.Dispose();
                hv_Column.Dispose();
                hv_Radius.Dispose();
                hv_ModelID.Dispose();
                }
            }
            MessageBox.Show("模板创建成功！");
            Form1_Load(null,null);
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            modelList.Items.Clear();
            DirectoryInfo dir = new DirectoryInfo("f:modelFiles/");
            DirectoryInfo[] subDirs = dir.GetDirectories();
            foreach (DirectoryInfo subDir in subDirs)
            {
                modelList.Items.Add(subDir.Name);
            }
            modelList.SelectedIndex = 0;
        }

        private void timer1_Tick(object sender, EventArgs e)
        {             
            checkModel();        }

        private void checkModel()
        {      
            HObject ho_Image1 = null;
            HTuple hv_Row = new HTuple();
            HTuple hv_Column = new HTuple();
            HTuple hv_Width = new HTuple(), hv_Height = new HTuple();
            HTuple hv_ModelID1 = new HTuple(), hv_ModelID2 = new HTuple();
            HTuple hv_ModelID3 = new HTuple(), hv_ModelID4 = new HTuple();
            HTuple hv_ModelIDs = new HTuple(), hv_Angle = new HTuple();
            HTuple hv_Score = new HTuple(), hv_ModelIndex = new HTuple();
            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_Image1);

            //Image Acquisition 01: Code generated by Image Acquisition 01
            HOperatorSet.GrabImageStart(hv_AcqHandle, -1);
           
            hv_ModelID1.Dispose();
            HOperatorSet.ReadShapeModel("f:modelFiles/"+modelList.SelectedItem.ToString()+"/modle1.shm", out hv_ModelID1);
            hv_ModelID2.Dispose();
            HOperatorSet.ReadShapeModel("f:modelFiles/" + modelList.SelectedItem.ToString() + "/modle2.shm", out hv_ModelID2);
            hv_ModelID3.Dispose();
            HOperatorSet.ReadShapeModel("f:modelFiles/" + modelList.SelectedItem.ToString() + "/modle3.shm", out hv_ModelID3);
            hv_ModelID4.Dispose();
            HOperatorSet.ReadShapeModel("f:modelFiles/" + modelList.SelectedItem.ToString() + "/modle4.shm", out hv_ModelID4);

            hv_ModelIDs.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_ModelIDs = new HTuple();
                hv_ModelIDs = hv_ModelIDs.TupleConcat(hv_ModelID1);
                hv_ModelIDs = hv_ModelIDs.TupleConcat(hv_ModelID2);
                hv_ModelIDs = hv_ModelIDs.TupleConcat(hv_ModelID3);
                hv_ModelIDs = hv_ModelIDs.TupleConcat(hv_ModelID4);
            }

                ho_Image1.Dispose();
                HOperatorSet.GrabImageAsync(out ho_Image1, hv_AcqHandle, -1);
                HOperatorSet.GetImageSize(ho_Image1, out hv_Width, out hv_Height);
                if (hWindowControl1.HalconWindow.ToString() == "") { return; }
                HOperatorSet.SetPart(hWindowControl1.HalconWindow, 0, 0, hv_Width+1, hv_Height+1);
                HOperatorSet.DispObj(ho_Image1, hWindowControl1.HalconWindow);
                hv_Row.Dispose(); hv_Column.Dispose(); hv_Angle.Dispose(); hv_Score.Dispose(); hv_ModelIndex.Dispose();
                HOperatorSet.FindShapeModels(ho_Image1, hv_ModelIDs, 0, (new HTuple(360)).TupleRad()
                    , 0.5, 8, 0.5, "least_squares", 0, 0.8, out hv_Row, out hv_Column, out hv_Angle,
                    out hv_Score, out hv_ModelIndex);

                if ((int)(new HTuple(hv_Score.TupleGreater(0))) != 0)
                {
                    pictureBox1.BackColor = Color.Green;
                    a++;
                    TrueNum.Text = a + "个";
                }
                else
                {
                    pictureBox1.BackColor = Color.Red;
                    b++;
                    WrongNum.Text = b + "个";
                }
                c = a + b;
                allNum.Text = c + "个";
                /* ho_Image1.Dispose();
                  hv_AcqHandle.Dispose();
                  hv_Row.Dispose();
                  hv_Column.Dispose();
                  hv_ModelID1.Dispose();
                  hv_ModelID2.Dispose();
                  hv_ModelID3.Dispose();
                  hv_ModelID4.Dispose();
                  hv_ModelIDs.Dispose();
                  hv_Angle.Dispose();
                  hv_Score.Dispose();
                  hv_ModelIndex.Dispose();*/
            }

            //if ((int)(new HTuple((new HTuple(hv_Row1.TupleLength())).TupleEqual(1))) != 0)                                  
        }
    }
